// User Roles and Dashboard Mappings based on NAZ structure

export const USER_ROLES = {
  // Executive
  DIRECTOR: 'DIRECTOR',
  DEPUTY_DIRECTOR_ARCHIVES: 'DEPUTY_DIRECTOR_ARCHIVES',
  DEPUTY_DIRECTOR_ADMIN: 'DEPUTY_DIRECTOR_ADMIN',

  // Processing
  CHIEF_ARCHIVIST: 'CHIEF_ARCHIVIST',
  GOVT_RECORDS_SPECIALIST: 'GOVT_RECORDS_SPECIALIST',
  RECORDS_MANAGEMENT_OFFICER: 'RECORDS_MANAGEMENT_OFFICER',
  ACCESSIONING_OFFICER: 'ACCESSIONING_OFFICER',
  CATALOGUING_OFFICER: 'CATALOGUING_OFFICER',
  RECORDS_CENTRE_OFFICER: 'RECORDS_CENTRE_OFFICER',

  // Preservation
  CHIEF_CONSERVATOR: 'CHIEF_CONSERVATOR',
  PAPER_CONSERVATOR: 'PAPER_CONSERVATOR',
  PHOTOGRAPHIC_CONSERVATOR: 'PHOTOGRAPHIC_CONSERVATOR',
  CONSERVATION_TECHNICIAN: 'CONSERVATION_TECHNICIAN',
  ENVIRONMENTAL_OFFICER: 'ENVIRONMENTAL_OFFICER',

  // Digital & ICT
  HEAD_DIGITAL_ARCHIVES: 'HEAD_DIGITAL_ARCHIVES',
  DIGITAL_ARCHIVIST: 'DIGITAL_ARCHIVIST',
  DIGITIZATION_OFFICER: 'DIGITIZATION_OFFICER',
  SYSTEMS_ADMINISTRATOR: 'SYSTEMS_ADMINISTRATOR',
  DATABASE_ADMINISTRATOR: 'DATABASE_ADMINISTRATOR',

  // Public Access
  HEAD_PUBLIC_SERVICES: 'HEAD_PUBLIC_SERVICES',
  REFERENCE_ARCHIVIST: 'REFERENCE_ARCHIVIST',
  READING_ROOM_SUPERVISOR: 'READING_ROOM_SUPERVISOR',
  RESEARCH_ASSISTANT: 'RESEARCH_ASSISTANT',
  REPROGRAPHICS_OFFICER: 'REPROGRAPHICS_OFFICER',

  // Audiovisual
  AUDIOVISUAL_ARCHIVIST: 'AUDIOVISUAL_ARCHIVIST',
  ORAL_HISTORY_COORDINATOR: 'ORAL_HISTORY_COORDINATOR',
  AV_TECHNICIAN: 'AV_TECHNICIAN',

  // Outreach
  OUTREACH_OFFICER: 'OUTREACH_OFFICER',
  EXHIBITIONS_CURATOR: 'EXHIBITIONS_CURATOR',
  PUBLICATIONS_OFFICER: 'PUBLICATIONS_OFFICER',
  COMMUNICATIONS_OFFICER: 'COMMUNICATIONS_OFFICER',

  // Admin & Corp Services
  HR_MANAGER: 'HR_MANAGER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  LEGAL_COMPLIANCE_OFFICER: 'LEGAL_COMPLIANCE_OFFICER',
  ADMINISTRATIVE_OFFICER: 'ADMINISTRATIVE_OFFICER',

  // Security
  SECURITY_MANAGER: 'SECURITY_MANAGER',
  SECURITY_OFFICER: 'SECURITY_OFFICER',
  FACILITIES_MANAGER: 'FACILITIES_MANAGER',
  MAINTENANCE_STAFF: 'MAINTENANCE_STAFF',

  // Provincial
  PROVINCIAL_ARCHIVIST: 'PROVINCIAL_ARCHIVIST',
  REGIONAL_RECORDS_OFFICER: 'REGIONAL_RECORDS_OFFICER',

  // Standard User
  PUBLIC: 'PUBLIC',
  REGISTERED_RESEARCHER: 'REGISTERED_RESEARCHER',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
} as const

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES]

// Role to Dashboard Mapping (Consolidated to major functional areas)
export const ROLE_DASHBOARD_MAP: Record<UserRole, string> = {
  [USER_ROLES.DIRECTOR]: '/dashboard/executive',
  [USER_ROLES.DEPUTY_DIRECTOR_ARCHIVES]: '/dashboard/executive',
  [USER_ROLES.DEPUTY_DIRECTOR_ADMIN]: '/dashboard/executive',
  [USER_ROLES.CHIEF_ARCHIVIST]: '/dashboard/processing',
  [USER_ROLES.GOVT_RECORDS_SPECIALIST]: '/dashboard/processing',
  [USER_ROLES.RECORDS_MANAGEMENT_OFFICER]: '/dashboard/processing',
  [USER_ROLES.ACCESSIONING_OFFICER]: '/dashboard/processing',
  [USER_ROLES.CATALOGUING_OFFICER]: '/dashboard/processing',
  [USER_ROLES.RECORDS_CENTRE_OFFICER]: '/dashboard/processing',
  [USER_ROLES.CHIEF_CONSERVATOR]: '/dashboard/preservation',
  [USER_ROLES.PAPER_CONSERVATOR]: '/dashboard/preservation',
  [USER_ROLES.PHOTOGRAPHIC_CONSERVATOR]: '/dashboard/preservation',
  [USER_ROLES.CONSERVATION_TECHNICIAN]: '/dashboard/preservation',
  [USER_ROLES.ENVIRONMENTAL_OFFICER]: '/dashboard/preservation',
  [USER_ROLES.HEAD_DIGITAL_ARCHIVES]: '/dashboard/tech',
  [USER_ROLES.DIGITAL_ARCHIVIST]: '/dashboard/tech',
  [USER_ROLES.DIGITIZATION_OFFICER]: '/dashboard/tech',
  [USER_ROLES.SYSTEMS_ADMINISTRATOR]: '/dashboard/tech',
  [USER_ROLES.DATABASE_ADMINISTRATOR]: '/dashboard/tech',
  [USER_ROLES.HEAD_PUBLIC_SERVICES]: '/dashboard/reference',
  [USER_ROLES.REFERENCE_ARCHIVIST]: '/dashboard/reference',
  [USER_ROLES.READING_ROOM_SUPERVISOR]: '/dashboard/reference',
  [USER_ROLES.RESEARCH_ASSISTANT]: '/dashboard/reference',
  [USER_ROLES.REPROGRAPHICS_OFFICER]: '/dashboard/reference',
  [USER_ROLES.AUDIOVISUAL_ARCHIVIST]: '/dashboard/specialist',
  [USER_ROLES.ORAL_HISTORY_COORDINATOR]: '/dashboard/specialist',
  [USER_ROLES.AV_TECHNICIAN]: '/dashboard/specialist',
  [USER_ROLES.OUTREACH_OFFICER]: '/dashboard/outreach',
  [USER_ROLES.EXHIBITIONS_CURATOR]: '/dashboard/outreach',
  [USER_ROLES.PUBLICATIONS_OFFICER]: '/dashboard/outreach',
  [USER_ROLES.COMMUNICATIONS_OFFICER]: '/dashboard/outreach',
  [USER_ROLES.HR_MANAGER]: '/dashboard/management',
  [USER_ROLES.FINANCE_OFFICER]: '/dashboard/management',
  [USER_ROLES.PROCUREMENT_OFFICER]: '/dashboard/management',
  [USER_ROLES.LEGAL_COMPLIANCE_OFFICER]: '/dashboard/management',
  [USER_ROLES.ADMINISTRATIVE_OFFICER]: '/dashboard/management',
  [USER_ROLES.SECURITY_MANAGER]: '/dashboard/security',
  [USER_ROLES.SECURITY_OFFICER]: '/dashboard/security',
  [USER_ROLES.FACILITIES_MANAGER]: '/dashboard/security',
  [USER_ROLES.MAINTENANCE_STAFF]: '/dashboard/security',
  [USER_ROLES.PROVINCIAL_ARCHIVIST]: '/dashboard/regional',
  [USER_ROLES.REGIONAL_RECORDS_OFFICER]: '/dashboard/regional',
  [USER_ROLES.PUBLIC]: '/',
  [USER_ROLES.REGISTERED_RESEARCHER]: '/dashboard/user',
  [USER_ROLES.SYSTEM_ADMIN]: '/dashboard/admin',
}

// Role Display Names
export const ROLE_DISPLAY_NAMES: Record<UserRole, string> = {
  [USER_ROLES.DIRECTOR]: 'Director',
  [USER_ROLES.DEPUTY_DIRECTOR_ARCHIVES]: 'Deputy Director (Archives)',
  [USER_ROLES.DEPUTY_DIRECTOR_ADMIN]: 'Deputy Director (Admin)',
  [USER_ROLES.CHIEF_ARCHIVIST]: 'Chief Archivist',
  [USER_ROLES.GOVT_RECORDS_SPECIALIST]: 'Archivist (Govt Records)',
  [USER_ROLES.RECORDS_MANAGEMENT_OFFICER]: 'Records Management Officer',
  [USER_ROLES.ACCESSIONING_OFFICER]: 'Accessioning Officer',
  [USER_ROLES.CATALOGUING_OFFICER]: 'Cataloguing Officer',
  [USER_ROLES.RECORDS_CENTRE_OFFICER]: 'Records Centre Officer',
  [USER_ROLES.CHIEF_CONSERVATOR]: 'Chief Conservator',
  [USER_ROLES.PAPER_CONSERVATOR]: 'Paper Conservator',
  [USER_ROLES.PHOTOGRAPHIC_CONSERVATOR]: 'Photographic Conservator',
  [USER_ROLES.CONSERVATION_TECHNICIAN]: 'Conservation Technician',
  [USER_ROLES.ENVIRONMENTAL_OFFICER]: 'Environmental Monitoring Officer',
  [USER_ROLES.HEAD_DIGITAL_ARCHIVES]: 'Head of Digital Archives',
  [USER_ROLES.DIGITAL_ARCHIVIST]: 'Digital Archivist',
  [USER_ROLES.DIGITIZATION_OFFICER]: 'Digitization Officer',
  [USER_ROLES.SYSTEMS_ADMINISTRATOR]: 'Systems Administrator',
  [USER_ROLES.DATABASE_ADMINISTRATOR]: 'Database Administrator',
  [USER_ROLES.HEAD_PUBLIC_SERVICES]: 'Head of Public Services',
  [USER_ROLES.REFERENCE_ARCHIVIST]: 'Reference Archivist',
  [USER_ROLES.READING_ROOM_SUPERVISOR]: 'Reading Room Supervisor',
  [USER_ROLES.RESEARCH_ASSISTANT]: 'Research Assistant',
  [USER_ROLES.REPROGRAPHICS_OFFICER]: 'Reprographics Officer',
  [USER_ROLES.AUDIOVISUAL_ARCHIVIST]: 'Audiovisual Archivist',
  [USER_ROLES.ORAL_HISTORY_COORDINATOR]: 'Oral History Coordinator',
  [USER_ROLES.AV_TECHNICIAN]: 'Audio-Visual Technician',
  [USER_ROLES.OUTREACH_OFFICER]: 'Outreach & Education Officer',
  [USER_ROLES.EXHIBITIONS_CURATOR]: 'Exhibitions Curator',
  [USER_ROLES.PUBLICATIONS_OFFICER]: 'Publications Officer',
  [USER_ROLES.COMMUNICATIONS_OFFICER]: 'Communications Officer',
  [USER_ROLES.HR_MANAGER]: 'Human Resources Manager',
  [USER_ROLES.FINANCE_OFFICER]: 'Finance Officer',
  [USER_ROLES.PROCUREMENT_OFFICER]: 'Procurement Officer',
  [USER_ROLES.LEGAL_COMPLIANCE_OFFICER]: 'Legal & Compliance Officer',
  [USER_ROLES.ADMINISTRATIVE_OFFICER]: 'Administrative Officer',
  [USER_ROLES.SECURITY_MANAGER]: 'Security Manager',
  [USER_ROLES.SECURITY_OFFICER]: 'Security Officer',
  [USER_ROLES.FACILITIES_MANAGER]: 'Facilities Manager',
  [USER_ROLES.MAINTENANCE_STAFF]: 'Maintenance Staff',
  [USER_ROLES.PROVINCIAL_ARCHIVIST]: 'Provincial Archivist',
  [USER_ROLES.REGIONAL_RECORDS_OFFICER]: 'Regional Records Officer',
  [USER_ROLES.PUBLIC]: 'Public User',
  [USER_ROLES.REGISTERED_RESEARCHER]: 'Registered Researcher',
  [USER_ROLES.SYSTEM_ADMIN]: 'System Administrator',
}

// Access Control (Renamed from Clearance)
export const ACCESS_CONTROL = {
  RESTRICTED: 'RESTRICTED',
  CONFIDENTIAL: 'CONFIDENTIAL',
  SECRET: 'SECRET',
  TOP_SECRET: 'TOP_SECRET',
  PUBLIC_ACCESS: 'PUBLIC_ACCESS',
} as const

export type AccessControl = (typeof ACCESS_CONTROL)[keyof typeof ACCESS_CONTROL]
